### ISSUE TITLE
phpcpp module not loading php version 5.3.3

### ISSUE THREAD

**Issue by ahmedghilman** [CopernicaMarketingSoftware/PHP-CPP-LEGACY#13]
Getting this error after putting libphpcpp.so into location /usr/lib64/php/modules/ and adding phpcpp.ini under /etc/php.d/phpcpp.ini.

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/libphpcpp.so' - /usr/lib64/php/modules/libphpcpp.so: undefined symbol      : _ZN3Php9StreamBuf4syncEv in Unknown on line 0
PHP 5.3.3 (cli) (built: Mar 22 2017 12:27:09)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

**Comment by masterseo2000** [comment]
I am having the same problem.... hopefully someone can help us

**Comment by masterseo2000** [comment]
Can someone answer this please?

**Comment by RafalGoslawski** [comment]
libphpcpp.so is not a PHP extension itself. It's a library to _create_ PHP extensions. It's supposed to be installed in /usr/lib/ or /usr/local/lib.  There's no phpcpp.ini.

**Comment by ahmedghilman** [comment]
OK Thanks Got it.
